### ISSUE TITLE
Add dnscan

### ISSUE THREAD

**Issue by exploitprotocol** [anshumanbh/brutesubs#9]
This is to decrease the computational time. I have seen enumall consume most of the time because it is single threaded scanner i guess. 

As far as i know, enumall first try to gather domains from bing, google and other sources like sublist3r, so i guess sublist3r is enough to fill that part and rest it only bruteforce subdomains through a wordlist. 

So i am recommeding second brutforce part with [dnscan](https://github.com/rbsec/dnscan), it is a multithreaded scanner(can support up to 32 thread).  I have checked myself and it is comparativley much faster than enumall. AFAIK only subbrute and dnscan have multi-threaded support. But subbrute hangs after some queries, so this would be perfect option.

**Comment by anshumanbh** [comment]
@exploitprotocol 

Enumall uses these modules:

- "recon/domains-hosts/threatcrowd",
- "recon/domains-hosts/hackertarget",
- "recon/domains-hosts/bing_domain_web",
- "recon/domains-hosts/google_site_web",
- "recon/domains-hosts/netcraft",  
- "recon/domains-hosts/shodan_hostname",
- "recon/domains-hosts/google_site_api"

Are you sure all these are covered under Sublist3r?

Also, Enumall follows redirects but I don't think DNSCAN does that so we will potentially be missing some domains that are found because of redirects. Can you confirm this is the case?

**Comment by exploitprotocol** [comment]
![screenshot_57](https://cloud.githubusercontent.com/assets/4075832/20806975/158662a2-b823-11e6-83e5-6777151137d4.png)
From the above picture, it looks like all modules are covered.

I don't know about redirects, but i have been using dnscan today and it is really fast, those threads really help.

**Comment by anshumanbh** [comment]
@exploitprotocol 

Yeah, I know dnscan is really fast. I did the comparison too. The only reason I am hesitant is because dnscan missed a few domains that enumall didn't. Plus, we would be missing out Shodan in enumall which can actually be pretty useful sometimes. 

I have a todo item to increase the computation time so if that is the primary reason for this feature request, I would rather improve the computation time in other ways than replace the tools. 

Thanks for looking into ways of improving the computation time though 👍 

I think I am pretty set on the toolset in brutesubs unless a new tool drops or the current breed changes drastically.
